### ISSUE TITLE
Feature: Native app

### ISSUE THREAD

**Issue by DonaldTsang** [mserajnik/hydrusrvue#2]
I have seen this online https://vue-native.io/ https://nativescript-vue.org/
Is it possible to make HydrusVue a phone app?

**Comment by DonaldTsang** [comment]
@mserajnik if it is responsive to phone screens then I can definitely warp it into an app.

**Comment by mserajnik** [comment]
It is, so feel free to. :)

**Comment by mserajnik** [comment]
The mobile web view already exists – the whole frontend is responsive. Try opening the [demo](https://hydrusrvue.mser.at) on a mobile device or use the devtools in a desktop browser to simulate a mobile device. :)

The whole frontend is completely decoupled from the hydrusrv server und 100% rendered in the frontend with Vue.

**Comment by DonaldTsang** [comment]
@mserajnik is it "render on browser/client with queries into server" or just a less concrete sense of frontend? Because when I read the source of hydrusrvue.mser.at there seems to be no explicit Vue imports like `<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>` (and instead hashed js files) and it leads me to think that this is more of a "thinner client" situation.

**Comment by mserajnik** [comment]
You need to bundle everything with webpack.

Afterwards, you end up with a bunch of HTML, CSS and JS files in the `dist` directory that you can just put on any web server – it's completely static, no code (PHP, Python or anything) needs to run on the server to serve the frontend.

See the [installation](https://github.com/mserajnik/hydrusrvue#install) and [usage](https://github.com/mserajnik/hydrusrvue#usage) sections in the readme for more detailed information.

**Comment by mserajnik** [comment]
Closed – see #8.
