### ISSUE TITLE
Add default colors for common namespaces

### ISSUE THREAD

**Issue by mserajnik** [mserajnik/hydrusrvue#4]
As mentioned [here](https://github.com/mserajnik/hydrusrv/issues/3#issuecomment-437481528), it would be good to have sensible default colors for common namespaces, so the user doesn't have to set it by hand for every new browser/device for it to look presentable/usable.

Two questions have to be answered before implementation:

1. Which are the common namespaces we want to set defaults for?
2. What should the default colors be?

In my opinion, we should use the same default namespaces hydrus itself uses. Colors could be adopted (and maybe slightly adjusted to fit better with the hydrusrvue theme, if needed) from a large and well-known booru like Danbooru.

@FredericaBernkastel, what do you think?

**Comment by FredericaBernkastel** [comment]
Everything is right.

**Comment by mserajnik** [comment]
Thanks, I'll implement it that way then. 👍
