### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by FredericaBernkastel** [mserajnik/hydrusrvue#6]
I think this will save alot of headache for new users (as long as they're not sysadmins).
[https://github.com/FredericaBernkastel/hydrusrvue/wiki/Example-nginx-configuration](https://github.com/FredericaBernkastel/hydrusrvue/wiki/Example-nginx-configuration)

**Comment by mserajnik** [comment]
Looks good, but I‘d probably rather add such an entry to hydrusrv since it‘s the main project and only mention it in the readmes of hydrusrvue and hydrusrv-docker.

Curious, when you serve the media files directly with nginx, don‘t you lose the `content-type` header (since the files have no file extension to guess the mime type from)?

**Comment by FredericaBernkastel** [comment]
Few problems:
1. "right click -> open image in new tab" will start downloading file instead of displaying it
2. "right click -> Save image as" won't have file extension

I'd still prefer nginx to serve static content, since it provides quite powerful tools to do that.
E.g. it can limit upload speed per IP. Imagine a single scraper eating all of 100Mbps bandwidth.

1st issue i've fixed with [**`default_type '';`**](https://github.com/FredericaBernkastel/hydrusrvue/wiki/Example-nginx-configuration/_compare/9b8a966b87e26f6b68e7f1d3b93eeea816383736...ec0300ed13445451137c6970c925bfbce4182fee) (remove the header). Browser will detect mime automatically, and display image again.

2nd problem can be solved aswell:
https://stackoverflow.com/a/16302092
(need to add `e.preventDefault` of click handler)

**Comment by mserajnik** [comment]
@FredericaBernkastel 

I've gotten an email notification that you've written a comment but it seems like you've either deleted it or there's a bug on GitHub. 🤔

**Comment by FredericaBernkastel** [comment]
Yeah, there is an issue due missing content-type. 
User can't open image in new tab, and file save dialog will miss extension.

[But i solved one!](https://github.com/FredericaBernkastel/hydrusrvue/wiki/Example-nginx-configuration/_compare/9b8a966b87e26f6b68e7f1d3b93eeea816383736...d2033c0ae6090623c3c9e24fa86d1cc7b575743c)

Nginx will make subrequest to hydrusrv, fetch mime-type, fix the content-type header, and send the file as regular.

Also, i noticed this:
https://github.com/mserajnik/hydrusrv/blob/8773173b5f581431812520103ba8f77a1daf3e55/server/util/media.js#L32

If you already have all metadata in db, what's the point to read the file and guess it's type by signatures?

**Comment by mserajnik** [comment]
The point is that it saves the blocking call to read the type from the DB. If a user were to load a page with 42 files, this would trigger 42 additional reads across all the workers, likely blocking all of them for a few ms.

I can‘t confirm your claim of up to 30ms. This takes around <1ms for me on an SSD, regardless of filesize (we are only reading the first 4100 bytes to be able read the magic number; although I‘ve noticed in a recent release of file-type, it‘s not supposed to be a hardcoded limit anymore, I‘ll adjust this soon).

**Comment by FredericaBernkastel** [comment]
How to make this function include proper file extension after hash?
https://github.com/mserajnik/hydrusrvue/blob/a5b1db11e6bd491e812e1d49e3017fea8285228c/src/views/File.vue#L137-L139
I'm not asking you to patch hydrusrvue, just need it for my fork (human-readable direct links).

**Comment by mserajnik** [comment]
You'd need to pass `this.file.mime` as a second parameter (so, `return urlFormatter.prepareMediaUrl(this.file.mediaUrl, this.file.mime)`) and then use that parameter to append the file extension after `url` via a mapping for _mime id -> extension_ here: https://github.com/mserajnik/hydrusrvue/blob/a5b1db11e6bd491e812e1d49e3017fea8285228c/src/util/url-formatter.js#L5-L9

You can copy the mapping from hydrusrv-sync [here](https://github.com/mserajnik/hydrusrv-sync/blob/10538b9bf235e7682c57ac4dcd761e4ae1bfaa63/src/config/index.js#L5-L17).

**Comment by mserajnik** [comment]
Actually, just noticed `file.mime` already has the mime in the form `image/png`, so you‘ll need to map that instead of the ID like in hydrusrv-sync.

**Comment by FredericaBernkastel** [comment]
Already done
FredericaBernkastel/hydrusrvue@2ee9cb3fffccbd40d0c7b7a8f6bbfb08128e3d9b

**Comment by mserajnik** [comment]
Closed – see #8.
